### ISSUE TITLE
VRE set position

### ISSUE THREAD

**Issue by agamemnonc** [biopatrec/biopatrec#13]
Is it possible to send a position command for one (or all) DOFs in VER?

That is, instead of sending a command about what action to take for a specified DOF, send a command about its desired position/angle.

**Comment by agamemnonc** [comment]
And relevant to the above, is there any way of querying the current position of one (or all) DOFs?

**Comment by casualformality** [comment]
Unfortunately, there are no methods to set a target position or query the current position. It is something we may add in the future, since it's a good idea, but there is currently no active development on the virtual reality environment.

As a workaround, there are hard limits and checks on the values for the positions, so you can send a command to fully extend a digit by sending a high value to reset it, and then send the target position.

**Comment by agamemnonc** [comment]
Thanks for the response. What would be considered as an extremely high value that would ensure the specified dof is fully extended?

**Comment by casualformality** [comment]
Hello @agamemnonc, 360 should be sufficient.

Also, I just remembered you can use the following command to completely reset the limb to its default position: 
fwrite(com,sprintf('%c%c%c%c','r','t',char(0),char(0)));
That way, you don't have to do it to individual DoFs if you want the whole thing reset.

**Comment by MB-Kristoffersen** [comment]
I am closing this issue since there has been no communication since 2019.
