### ISSUE TITLE
TAC Test VRE crash

### ISSUE THREAD

**Issue by mheeniac** [biopatrec/biopatrec#7]
Good morning, 

I am trying to perform a TAC Test. The classifier works when running 'Test Real-time PatRec' and when performing a Motion Test. However, when I try to run the TAC Test my VRE environment does not update. I get the green arm that shows what movement to do but the grey one does not move. I also get the following error in matlab: 

Warning: Error occurred while executing callback:
Undefined function 'EuclidDist' for input arguments of type 'double'.

Has anyone encountered this and/or knows how to fix it? 

Thank you in advance!

**Comment by maxoc** [comment]
Hi,
It seems like that file was forgotten in the last release due to interference with one of the patrec algorithms. Please add the function attached to the VRE folder and then it should work. This will be fixed in the next release of BioPatRec

[EuclidDist.zip](https://github.com/biopatrec/biopatrec/files/246612/EuclidDist.zip)

.

**Comment by mheeniac** [comment]
Thank you, this solved it!
